name 'synyx-graylog2'
version '0.5.1'
author 'Johannes Graf'
license 'MIT License'
project_page 'https://github.com/synyx/puppet-graylog2'
source 'https://github.com/synyx/puppet-graylog2.git'
summary 'Puppet module to install and manage a graylog2 server and the web-interface'
description 'A Puppet module to install and manage a graylog2 server and the web-interface'
dependency 'puppetlabs/stdlib', '>=0.0.1'
dependency 'puppetlabs/apt', '>=0.0.1'
